# https://taskfile.dev

version: "3"

includes:
  sf: ./taskfiles/sf.yml
  dbt: ./taskfiles/dbt.yml
  preset: ./taskfiles/preset.yml
  dagster: ./taskfiles/dagster.yml

tasks:
  init-git-repo:
    cmds:
      - git init
    status:
      - test -d .git
    internal: true

  create-env-file:
    cmds:
      - cp .env.example .env
    status:
      - test -f .env
    internal: true

  create-tfvars-file:
    dir: infra
    cmds:
      - cp terraform.tfvars.example terraform.tfvars
    status:
      - test -f terraform.tfvars
    internal: true

  create-dbt-profile-file:
    dir: analytics/dbtbnb
    cmds:
      - cp profiles.yml.example profiles.yml
    status:
      - test -f profiles.yml
    internal: true

  create-data-dir:
    cmds:
      - mkdir -p data
    status:
      - test -d data
    internal: true

  setup:
    cmds:
      - task: init-git-repo
      - task: create-env-file
      - task: create-tfvars-file
      - task: create-dbt-profile-file
      - task: create-data-dir
      - task: dbt:get-seed-file
      - uv sync --all-groups --all-extras
      - uv run pre-commit install
    desc: Setup development environment

  setup-ci:
    cmds:
      - uv sync --all-groups --all-extras
      - uv run pre-commit install
    desc: Setup CI environment

  lint:
    cmds:
      - uv run pre-commit run --all-files
    desc: Run linters

  test:
    cmds:
      - uv run pytest
    desc: Run tests

  bump-version:
    cmds:
      - uv version --bump {{.BUMP}}
      - git tag v$(uv version --short)
    requires:
      vars:
        - name: BUMP
          enum: [patch, minor, major]
    desc: Bump project version
