models:
  - name: dim_listings_cleansed
    description: "Cleansed listing data from Airbnb"
    config:
      contract:
        enforced: true
    columns:
      - name: LISTING_ID
        data_type: string
        data_tests:
          - unique
          - not_null
      - name: LISTING_NAME
        data_type: string
      - name: ROOM_TYPE
        data_type: string
        data_tests:
          - accepted_values:
              arguments:
                values:
                  - Entire home/apt
                  - Private room
                  - Shared room
                  - Hotel room
      - name: HOST_ID
        data_type: number
        data_tests:
          - not_null
          - relationships:
              arguments:
                field: HOST_ID
                to: ref('dim_hosts_cleansed')
      - name: PRICE
        data_type: number
      - name: CREATED_AT
        data_type: timestamp
      - name: UPDATED_AT
        data_type: timestamp
      - name: MINIMUM_NIGHTS
        data_type: number
        data_tests:
          - positive_value_only

  - name: dim_hosts_cleansed
    description: "Cleansed host data from Airbnb"
    config:
      contract:
        enforced: true
    columns:
      - name: HOST_ID
        data_type: integer
      - name: IS_SUPERHOST
        data_type: string
      - name: CREATED_AT
        data_type: timestamp
      - name: UPDATED_AT
        data_type: timestamp
      - name: HOST_NAME
        data_type: string

  - name: dim_listings_with_hosts
    description: "Cleansed listing and host data from Airbnb"

  - name: fct_reviews
    description: "Fact table for reviews"
    data_tests:
      - min_row_count:
          arguments:
            row_count: 1000

  - name: mart_full_moon_reviews
    description: "Mart for full moon reviews"
    data_tests:
      - min_row_count:
          arguments:
            row_count: 1000
