version: 2

sources:
  - name: AIRBNB
    schema: RAW
    tables:
      - name: LISTINGS
        identifier: RAW_LISTINGS
      - name: REVIEWS
        identifier: RAW_REVIEWS
        config:
          loaded_at_field: DATE
          freshness:
            warn_after:
              count: 1
              period: hour
      - name: HOSTS
        identifier: RAW_HOSTS
