WITH raw_listings AS (
    SELECT * FROM {{ source("AIRBNB", "LISTINGS") }}
)
SELECT
    ID AS LISTING_ID,
    NAME as LISTING_NAME,
    LISTING_URL,
    ROOM_TYPE,
    MINIMUM_NIGHTS,
    HOST_ID,
    PRICE AS PRICE_STR,
    CREATED_AT,
    UPDATED_AT
FROM
    raw_listings
