WITH raw_reviews AS (
    SELECT * FROM {{ source("AIRBNB", "REVIEWS") }}
)
SELECT
    ID,
    DATE AS REVIEW_DATE,
    REVIEWER_NAME,
    COMMENTS AS REVIEW_TEXT,
    SENTIMENT AS REVIEW_SENTIMENT
FROM
    raw_reviews
