USE DATABASE <%DB_NAME%>;
USE SCHEMA <%SCHEMA_NAME%>;

COPY INTO RAW_LISTINGS
FROM @<%STAGE_NAME%>/listings.csv
FILE_FORMAT = (FORMAT_NAME = '<%FILE_FORMAT%>');

COPY INTO RAW_REVIEWS
FROM @<%STAGE_NAME%>/reviews.csv
FILE_FORMAT = (FORMAT_NAME = '<%FILE_FORMAT%>');

COPY INTO RAW_HOSTS
FROM @<%STAGE_NAME%>/hosts.csv
FILE_FORMAT = (FORMAT_NAME = '<%FILE_FORMAT%>');
