USE ROLE ACCOUNTADMIN;

CREATE USER TERRAFORM
    TYPE = SERVICE
    COMMENT = "Terraform service user"
    RSA_PUBLIC_KEY = "<%PUBLIC_KEY%>";

GRANT ROLE SYSADMIN TO USER TERRAFORM;
GRANT ROLE SECURITYADMIN TO USER TERRAFORM;
