WITH
LISTINGS AS (
    SELECT * FROM {{ ref("dim_listings_cleansed") }}
),

HOSTS AS (
    SELECT * FROM {{ ref("dim_hosts_cleansed") }}
)

SELECT
    LISTINGS.LISTING_ID,
    LISTINGS.LISTING_NAME,
    LISTINGS.ROOM_TYPE,
    LISTINGS.MINIMUM_NIGHTS,
    LISTINGS.PRICE,
    LISTINGS.HOST_ID,
    HOSTS.HOST_NAME,
    HOSTS.IS_SUPERHOST AS HOST_IS_SUPERHOST,
    LISTINGS.CREATED_AT,
    GREATEST(LISTINGS.UPDATED_AT, HOSTS.UPDATED_AT) AS UPDATED_AT
FROM LISTINGS
LEFT JOIN HOSTS ON (LISTINGS.HOST_ID = HOSTS.HOST_ID)
